### Variables
@baseUrl = http://localhost:7071
@functionKey =

### Get Random Joke
GET {{baseUrl}}/api/jokes/random
Content-Type: application/json

###

### Save New Joke - Example 1
POST {{baseUrl}}/api/jokes
Content-Type: application/json

{
  "joke": "Chuck Norris can compile syntax errors."
}

###

### Save New Joke - Example 2 (without URL)
POST {{baseUrl}}/api/jokes
Content-Type: application/json

{
  "joke": "Chuck Norris doesn't need a debugger. Bugs fix themselves when they see him coming."
}

###

### Save New Joke - Example 3
POST {{baseUrl}}/api/jokes
Content-Type: application/json

{
  "joke": "Chuck Norris writes code that optimizes itself."
}

###

### Test Error Handling - Empty Joke
POST {{baseUrl}}/api/jokes
Content-Type: application/json

{
  "joke": ""
}

###

###
